name: clients
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  razorpay_flutter: ^1.4.0
  fluttertoast: ^8.2.4
  confetti: ^0.6.0
  flutter_credit_card: ^3.0.0
  lottie: ^2.6.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.3
  image_picker: ^0.8.4+4
  intl: ^0.20.2
  flutter_rating_bar: ^4.0.1
  geolocator: ^13.0.3
  latlong2: ^0.9.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/config.json
